[mypy]
python_version = 3.12
mypy_path = .
exclude = ^python/aim/bus/v1/
strict = True
warn_return_any = True
warn_unused_configs = True

[mypy-flatbuffers.*]
ignore_missing_imports = True

[mypy-aim.bus.v1.*]
ignore_missing_imports = True

[mypy-tools.probe.*]
disable_error_code = attr-defined

[mypy-tools.timing.clock]
disable_error_code = attr-defined
