from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.ButtonTransition import ButtonTransition
from aim.bus.v1.CorrelationHeader import CorrelationHeader

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ActuationCommand:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ActuationCommand: ...
  @classmethod
  def GetRootAsActuationCommand(cls, buf: bytes, offset: int) -> ActuationCommand: ...
  @classmethod
  def ActuationCommandBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaMajor(self) -> int: ...
  def SchemaMinor(self) -> int: ...
  def Header(self) -> CorrelationHeader | None: ...
  def GeneratedAtNs(self) -> int: ...
  def DesiredApplyTimeNs(self) -> int: ...
  def DeltaXCounts(self) -> int: ...
  def DeltaYCounts(self) -> int: ...
  def ButtonTransition(self) -> ButtonTransition | None: ...
  def CancelSuperseded(self) -> bool: ...
def ActuationCommandStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ActuationCommandAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int) -> None: ...
def ActuationCommandAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int) -> None: ...
def ActuationCommandAddHeader(builder: flatbuffers.Builder, header: uoffset) -> None: ...
def ActuationCommandAddGeneratedAtNs(builder: flatbuffers.Builder, generatedAtNs: int) -> None: ...
def ActuationCommandAddDesiredApplyTimeNs(builder: flatbuffers.Builder, desiredApplyTimeNs: int) -> None: ...
def ActuationCommandAddDeltaXCounts(builder: flatbuffers.Builder, deltaXCounts: int) -> None: ...
def ActuationCommandAddDeltaYCounts(builder: flatbuffers.Builder, deltaYCounts: int) -> None: ...
def ActuationCommandAddButtonTransition(builder: flatbuffers.Builder, buttonTransition: uoffset) -> None: ...
def ActuationCommandAddCancelSuperseded(builder: flatbuffers.Builder, cancelSuperseded: bool) -> None: ...
def ActuationCommandEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
