# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.ButtonTransition import ButtonTransition
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from typing import Optional
np = import_numpy()

# @brief Canonical low-latency actuation command
class ActuationCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ActuationCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsActuationCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ActuationCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x41\x43\x31", size_prefixed=size_prefixed)

    # ActuationCommand
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ActuationCommand
    def SchemaMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # ActuationCommand
    def SchemaMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ActuationCommand
    def Header(self) -> Optional[CorrelationHeader]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = CorrelationHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ActuationCommand
    def GeneratedAtNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ActuationCommand
    def DesiredApplyTimeNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ActuationCommand
    def DeltaXCounts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ActuationCommand
    def DeltaYCounts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ActuationCommand
    def ButtonTransition(self) -> Optional[ButtonTransition]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ButtonTransition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ActuationCommand
    def CancelSuperseded(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def ActuationCommandStart(builder: flatbuffers.Builder):
    builder.StartObject(9)

def Start(builder: flatbuffers.Builder):
    ActuationCommandStart(builder)

def ActuationCommandAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    builder.PrependUint16Slot(0, schemaMajor, 1)

def AddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    ActuationCommandAddSchemaMajor(builder, schemaMajor)

def ActuationCommandAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    builder.PrependUint16Slot(1, schemaMinor, 0)

def AddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    ActuationCommandAddSchemaMinor(builder, schemaMinor)

def ActuationCommandAddHeader(builder: flatbuffers.Builder, header: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)

def AddHeader(builder: flatbuffers.Builder, header: int):
    ActuationCommandAddHeader(builder, header)

def ActuationCommandAddGeneratedAtNs(builder: flatbuffers.Builder, generatedAtNs: int):
    builder.PrependInt64Slot(3, generatedAtNs, 0)

def AddGeneratedAtNs(builder: flatbuffers.Builder, generatedAtNs: int):
    ActuationCommandAddGeneratedAtNs(builder, generatedAtNs)

def ActuationCommandAddDesiredApplyTimeNs(builder: flatbuffers.Builder, desiredApplyTimeNs: int):
    builder.PrependInt64Slot(4, desiredApplyTimeNs, 0)

def AddDesiredApplyTimeNs(builder: flatbuffers.Builder, desiredApplyTimeNs: int):
    ActuationCommandAddDesiredApplyTimeNs(builder, desiredApplyTimeNs)

def ActuationCommandAddDeltaXCounts(builder: flatbuffers.Builder, deltaXCounts: int):
    builder.PrependInt32Slot(5, deltaXCounts, 0)

def AddDeltaXCounts(builder: flatbuffers.Builder, deltaXCounts: int):
    ActuationCommandAddDeltaXCounts(builder, deltaXCounts)

def ActuationCommandAddDeltaYCounts(builder: flatbuffers.Builder, deltaYCounts: int):
    builder.PrependInt32Slot(6, deltaYCounts, 0)

def AddDeltaYCounts(builder: flatbuffers.Builder, deltaYCounts: int):
    ActuationCommandAddDeltaYCounts(builder, deltaYCounts)

def ActuationCommandAddButtonTransition(builder: flatbuffers.Builder, buttonTransition: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(buttonTransition), 0)

def AddButtonTransition(builder: flatbuffers.Builder, buttonTransition: int):
    ActuationCommandAddButtonTransition(builder, buttonTransition)

def ActuationCommandAddCancelSuperseded(builder: flatbuffers.Builder, cancelSuperseded: bool):
    builder.PrependBoolSlot(8, cancelSuperseded, 1)

def AddCancelSuperseded(builder: flatbuffers.Builder, cancelSuperseded: bool):
    ActuationCommandAddCancelSuperseded(builder, cancelSuperseded)

def ActuationCommandEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ActuationCommandEnd(builder)
