from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.AimMode import AimMode
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.Vec2f import Vec2f

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class AimIntent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> AimIntent: ...
  @classmethod
  def GetRootAsAimIntent(cls, buf: bytes, offset: int) -> AimIntent: ...
  @classmethod
  def AimIntentBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaMajor(self) -> int: ...
  def SchemaMinor(self) -> int: ...
  def Header(self) -> CorrelationHeader | None: ...
  def TargetTrackId(self) -> int: ...
  def Mode(self) -> typing.Literal[AimMode.Idle, AimMode.Tracking, AimMode.Flick, AimMode.MicroCorrection, AimMode.EmergencyHold]: ...
  def TargetAimPx(self) -> Vec2f | None: ...
  def TargetAimNorm(self) -> Vec2f | None: ...
  def LeadOffsetPx(self) -> Vec2f | None: ...
  def ErrorDistancePx(self) -> float: ...
  def AuthorizeFire(self) -> bool: ...
  def Confidence(self) -> float: ...
  def UtilityScore(self) -> float: ...
  def CommandDeadlineNs(self) -> int: ...
def AimIntentStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def AimIntentAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int) -> None: ...
def AimIntentAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int) -> None: ...
def AimIntentAddHeader(builder: flatbuffers.Builder, header: uoffset) -> None: ...
def AimIntentAddTargetTrackId(builder: flatbuffers.Builder, targetTrackId: int) -> None: ...
def AimIntentAddMode(builder: flatbuffers.Builder, mode: typing.Literal[AimMode.Idle, AimMode.Tracking, AimMode.Flick, AimMode.MicroCorrection, AimMode.EmergencyHold]) -> None: ...
def AimIntentAddTargetAimPx(builder: flatbuffers.Builder, targetAimPx: uoffset) -> None: ...
def AimIntentAddTargetAimNorm(builder: flatbuffers.Builder, targetAimNorm: uoffset) -> None: ...
def AimIntentAddLeadOffsetPx(builder: flatbuffers.Builder, leadOffsetPx: uoffset) -> None: ...
def AimIntentAddErrorDistancePx(builder: flatbuffers.Builder, errorDistancePx: float) -> None: ...
def AimIntentAddAuthorizeFire(builder: flatbuffers.Builder, authorizeFire: bool) -> None: ...
def AimIntentAddConfidence(builder: flatbuffers.Builder, confidence: float) -> None: ...
def AimIntentAddUtilityScore(builder: flatbuffers.Builder, utilityScore: float) -> None: ...
def AimIntentAddCommandDeadlineNs(builder: flatbuffers.Builder, commandDeadlineNs: int) -> None: ...
def AimIntentEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
