# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.Vec2f import Vec2f
from typing import Optional
np = import_numpy()

# @brief Aim intent computed by utility policy
class AimIntent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AimIntent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAimIntent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AimIntentBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x41\x49\x31", size_prefixed=size_prefixed)

    # AimIntent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AimIntent
    def SchemaMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # AimIntent
    def SchemaMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # AimIntent
    def Header(self) -> Optional[CorrelationHeader]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = CorrelationHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AimIntent
    def TargetTrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # AimIntent
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # AimIntent
    def TargetAimPx(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AimIntent
    def TargetAimNorm(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AimIntent
    def LeadOffsetPx(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AimIntent
    def ErrorDistancePx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AimIntent
    def AuthorizeFire(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # AimIntent
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # AimIntent
    def UtilityScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # AimIntent
    def CommandDeadlineNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def AimIntentStart(builder: flatbuffers.Builder):
    builder.StartObject(13)

def Start(builder: flatbuffers.Builder):
    AimIntentStart(builder)

def AimIntentAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    builder.PrependUint16Slot(0, schemaMajor, 1)

def AddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    AimIntentAddSchemaMajor(builder, schemaMajor)

def AimIntentAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    builder.PrependUint16Slot(1, schemaMinor, 0)

def AddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    AimIntentAddSchemaMinor(builder, schemaMinor)

def AimIntentAddHeader(builder: flatbuffers.Builder, header: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)

def AddHeader(builder: flatbuffers.Builder, header: int):
    AimIntentAddHeader(builder, header)

def AimIntentAddTargetTrackId(builder: flatbuffers.Builder, targetTrackId: int):
    builder.PrependUint64Slot(3, targetTrackId, 0)

def AddTargetTrackId(builder: flatbuffers.Builder, targetTrackId: int):
    AimIntentAddTargetTrackId(builder, targetTrackId)

def AimIntentAddMode(builder: flatbuffers.Builder, mode: int):
    builder.PrependUint8Slot(4, mode, 1)

def AddMode(builder: flatbuffers.Builder, mode: int):
    AimIntentAddMode(builder, mode)

def AimIntentAddTargetAimPx(builder: flatbuffers.Builder, targetAimPx: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(targetAimPx), 0)

def AddTargetAimPx(builder: flatbuffers.Builder, targetAimPx: Any):
    AimIntentAddTargetAimPx(builder, targetAimPx)

def AimIntentAddTargetAimNorm(builder: flatbuffers.Builder, targetAimNorm: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(targetAimNorm), 0)

def AddTargetAimNorm(builder: flatbuffers.Builder, targetAimNorm: Any):
    AimIntentAddTargetAimNorm(builder, targetAimNorm)

def AimIntentAddLeadOffsetPx(builder: flatbuffers.Builder, leadOffsetPx: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(leadOffsetPx), 0)

def AddLeadOffsetPx(builder: flatbuffers.Builder, leadOffsetPx: Any):
    AimIntentAddLeadOffsetPx(builder, leadOffsetPx)

def AimIntentAddErrorDistancePx(builder: flatbuffers.Builder, errorDistancePx: float):
    builder.PrependFloat32Slot(8, errorDistancePx, 0.0)

def AddErrorDistancePx(builder: flatbuffers.Builder, errorDistancePx: float):
    AimIntentAddErrorDistancePx(builder, errorDistancePx)

def AimIntentAddAuthorizeFire(builder: flatbuffers.Builder, authorizeFire: bool):
    builder.PrependBoolSlot(9, authorizeFire, 0)

def AddAuthorizeFire(builder: flatbuffers.Builder, authorizeFire: bool):
    AimIntentAddAuthorizeFire(builder, authorizeFire)

def AimIntentAddConfidence(builder: flatbuffers.Builder, confidence: float):
    builder.PrependFloat32Slot(10, confidence, 1.0)

def AddConfidence(builder: flatbuffers.Builder, confidence: float):
    AimIntentAddConfidence(builder, confidence)

def AimIntentAddUtilityScore(builder: flatbuffers.Builder, utilityScore: float):
    builder.PrependFloat32Slot(11, utilityScore, 1.0)

def AddUtilityScore(builder: flatbuffers.Builder, utilityScore: float):
    AimIntentAddUtilityScore(builder, utilityScore)

def AimIntentAddCommandDeadlineNs(builder: flatbuffers.Builder, commandDeadlineNs: int):
    builder.PrependInt64Slot(12, commandDeadlineNs, 0)

def AddCommandDeadlineNs(builder: flatbuffers.Builder, commandDeadlineNs: int):
    AimIntentAddCommandDeadlineNs(builder, commandDeadlineNs)

def AimIntentEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AimIntentEnd(builder)
