# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Aim controller operational mode
class AimMode(object):
    Idle = 0
    Tracking = 1
    Flick = 2
    MicroCorrection = 3
    EmergencyHold = 4
