from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BBoxf:
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Left(self) -> float: ...
  def Top(self) -> float: ...
  def Right(self) -> float: ...
  def Bottom(self) -> float: ...

def CreateBBoxf(builder: flatbuffers.Builder, left: float, top: float, right: float, bottom: float) -> uoffset: ...
