# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# @brief Mouse button state change request
class ButtonTransition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ButtonTransition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsButtonTransition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ButtonTransitionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x41\x43\x31", size_prefixed=size_prefixed)

    # ButtonTransition
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ButtonTransition
    def Button(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ButtonTransition
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ButtonTransitionStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    ButtonTransitionStart(builder)

def ButtonTransitionAddButton(builder: flatbuffers.Builder, button: int):
    builder.PrependUint8Slot(0, button, 0)

def AddButton(builder: flatbuffers.Builder, button: int):
    ButtonTransitionAddButton(builder, button)

def ButtonTransitionAddAction(builder: flatbuffers.Builder, action: int):
    builder.PrependUint8Slot(1, action, 0)

def AddAction(builder: flatbuffers.Builder, action: int):
    ButtonTransitionAddAction(builder, action)

def ButtonTransitionEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ButtonTransitionEnd(builder)
