# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Mouse button actuation action
class ButtonAction(object):
    None_ = 0
    Press = 1
    Release = 2
    Click = 3
