from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.ButtonAction import ButtonAction
from aim.bus.v1.MouseButton import MouseButton

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ButtonTransition:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ButtonTransition: ...
  @classmethod
  def GetRootAsButtonTransition(cls, buf: bytes, offset: int) -> ButtonTransition: ...
  @classmethod
  def ButtonTransitionBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Button(self) -> typing.Literal[MouseButton.None_, MouseButton.Left, MouseButton.Right, MouseButton.Middle, MouseButton.X1, MouseButton.X2]: ...
  def Action(self) -> typing.Literal[ButtonAction.None_, ButtonAction.Press, ButtonAction.Release, ButtonAction.Click]: ...
def ButtonTransitionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ButtonTransitionAddButton(builder: flatbuffers.Builder, button: typing.Literal[MouseButton.None_, MouseButton.Left, MouseButton.Right, MouseButton.Middle, MouseButton.X1, MouseButton.X2]) -> None: ...
def ButtonTransitionAddAction(builder: flatbuffers.Builder, action: typing.Literal[ButtonAction.None_, ButtonAction.Press, ButtonAction.Release, ButtonAction.Click]) -> None: ...
def ButtonTransitionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
