# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Coordinate space convention
class CoordinateSpace(object):
    PixelTopLeft = 0
    NormalizedCenter = 1
    CameraSpherical = 2
