from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class CorrelationHeader:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> CorrelationHeader: ...
  @classmethod
  def GetRootAsCorrelationHeader(cls, buf: bytes, offset: int) -> CorrelationHeader: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SequenceId(self) -> int: ...
  def SourceTimestampNs(self) -> int: ...
  def PipelineRunId(self) -> int: ...
  def Flags(self) -> int: ...
def CorrelationHeaderStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def CorrelationHeaderAddSequenceId(builder: flatbuffers.Builder, sequenceId: int) -> None: ...
def CorrelationHeaderAddSourceTimestampNs(builder: flatbuffers.Builder, sourceTimestampNs: int) -> None: ...
def CorrelationHeaderAddPipelineRunId(builder: flatbuffers.Builder, pipelineRunId: int) -> None: ...
def CorrelationHeaderAddFlags(builder: flatbuffers.Builder, flags: int) -> None: ...
def CorrelationHeaderEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
