# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# @brief Monotonic correlation header propagated across all pipeline stages
class CorrelationHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CorrelationHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCorrelationHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CorrelationHeader
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CorrelationHeader
    def SequenceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CorrelationHeader
    def SourceTimestampNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CorrelationHeader
    def PipelineRunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CorrelationHeader
    def Flags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def CorrelationHeaderStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    CorrelationHeaderStart(builder)

def CorrelationHeaderAddSequenceId(builder: flatbuffers.Builder, sequenceId: int):
    builder.PrependUint64Slot(0, sequenceId, 0)

def AddSequenceId(builder: flatbuffers.Builder, sequenceId: int):
    CorrelationHeaderAddSequenceId(builder, sequenceId)

def CorrelationHeaderAddSourceTimestampNs(builder: flatbuffers.Builder, sourceTimestampNs: int):
    builder.PrependInt64Slot(1, sourceTimestampNs, 0)

def AddSourceTimestampNs(builder: flatbuffers.Builder, sourceTimestampNs: int):
    CorrelationHeaderAddSourceTimestampNs(builder, sourceTimestampNs)

def CorrelationHeaderAddPipelineRunId(builder: flatbuffers.Builder, pipelineRunId: int):
    builder.PrependUint32Slot(2, pipelineRunId, 0)

def AddPipelineRunId(builder: flatbuffers.Builder, pipelineRunId: int):
    CorrelationHeaderAddPipelineRunId(builder, pipelineRunId)

def CorrelationHeaderAddFlags(builder: flatbuffers.Builder, flags: int):
    builder.PrependUint32Slot(3, flags, 0)

def AddFlags(builder: flatbuffers.Builder, flags: int):
    CorrelationHeaderAddFlags(builder, flags)

def CorrelationHeaderEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CorrelationHeaderEnd(builder)
