# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Diagnostic & synthetic correlation flags
class CorrelationFlags(object):
    None_ = 0
    Synthetic = 1
    Warmup = 2
    Dropped = 4
    TraceVerbose = 8
