# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# @brief Symmetric 2D covariance matrix in pixel^2
class Covariance2f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 12

    # Covariance2f
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Covariance2f
    def Xx(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Covariance2f
    def Xy(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Covariance2f
    def Yy(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateCovariance2f(builder, xx, xy, yy):
    builder.Prep(4, 12)
    builder.PrependFloat32(yy)
    builder.PrependFloat32(xy)
    builder.PrependFloat32(xx)
    return builder.Offset()
