# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from typing import Optional
np = import_numpy()

# @brief GPU/Shared memory frame lease descriptor
class FrameDescriptor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FrameDescriptor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFrameDescriptor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FrameDescriptorBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x46\x52\x31", size_prefixed=size_prefixed)

    # FrameDescriptor
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FrameDescriptor
    def SchemaMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # FrameDescriptor
    def SchemaMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FrameDescriptor
    def Header(self) -> Optional[CorrelationHeader]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = CorrelationHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FrameDescriptor
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FrameDescriptor
    def CapturedAtNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FrameDescriptor
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1920

    # FrameDescriptor
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1080

    # FrameDescriptor
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # FrameDescriptor
    def PoolSlotIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FrameDescriptor
    def SharedNtHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FrameDescriptor
    def AdapterLuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FrameDescriptor
    def IsKeyframe(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

def FrameDescriptorStart(builder: flatbuffers.Builder):
    builder.StartObject(12)

def Start(builder: flatbuffers.Builder):
    FrameDescriptorStart(builder)

def FrameDescriptorAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    builder.PrependUint16Slot(0, schemaMajor, 1)

def AddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    FrameDescriptorAddSchemaMajor(builder, schemaMajor)

def FrameDescriptorAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    builder.PrependUint16Slot(1, schemaMinor, 0)

def AddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    FrameDescriptorAddSchemaMinor(builder, schemaMinor)

def FrameDescriptorAddHeader(builder: flatbuffers.Builder, header: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)

def AddHeader(builder: flatbuffers.Builder, header: int):
    FrameDescriptorAddHeader(builder, header)

def FrameDescriptorAddFrameId(builder: flatbuffers.Builder, frameId: int):
    builder.PrependUint64Slot(3, frameId, 0)

def AddFrameId(builder: flatbuffers.Builder, frameId: int):
    FrameDescriptorAddFrameId(builder, frameId)

def FrameDescriptorAddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int):
    builder.PrependInt64Slot(4, capturedAtNs, 0)

def AddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int):
    FrameDescriptorAddCapturedAtNs(builder, capturedAtNs)

def FrameDescriptorAddWidth(builder: flatbuffers.Builder, width: int):
    builder.PrependUint32Slot(5, width, 1920)

def AddWidth(builder: flatbuffers.Builder, width: int):
    FrameDescriptorAddWidth(builder, width)

def FrameDescriptorAddHeight(builder: flatbuffers.Builder, height: int):
    builder.PrependUint32Slot(6, height, 1080)

def AddHeight(builder: flatbuffers.Builder, height: int):
    FrameDescriptorAddHeight(builder, height)

def FrameDescriptorAddFormat(builder: flatbuffers.Builder, format: int):
    builder.PrependUint8Slot(7, format, 1)

def AddFormat(builder: flatbuffers.Builder, format: int):
    FrameDescriptorAddFormat(builder, format)

def FrameDescriptorAddPoolSlotIndex(builder: flatbuffers.Builder, poolSlotIndex: int):
    builder.PrependUint32Slot(8, poolSlotIndex, 0)

def AddPoolSlotIndex(builder: flatbuffers.Builder, poolSlotIndex: int):
    FrameDescriptorAddPoolSlotIndex(builder, poolSlotIndex)

def FrameDescriptorAddSharedNtHandle(builder: flatbuffers.Builder, sharedNtHandle: int):
    builder.PrependUint64Slot(9, sharedNtHandle, 0)

def AddSharedNtHandle(builder: flatbuffers.Builder, sharedNtHandle: int):
    FrameDescriptorAddSharedNtHandle(builder, sharedNtHandle)

def FrameDescriptorAddAdapterLuid(builder: flatbuffers.Builder, adapterLuid: int):
    builder.PrependUint64Slot(10, adapterLuid, 0)

def AddAdapterLuid(builder: flatbuffers.Builder, adapterLuid: int):
    FrameDescriptorAddAdapterLuid(builder, adapterLuid)

def FrameDescriptorAddIsKeyframe(builder: flatbuffers.Builder, isKeyframe: bool):
    builder.PrependBoolSlot(11, isKeyframe, 1)

def AddIsKeyframe(builder: flatbuffers.Builder, isKeyframe: bool):
    FrameDescriptorAddIsKeyframe(builder, isKeyframe)

def FrameDescriptorEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FrameDescriptorEnd(builder)
