# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Captured frame pixel format
class FramePixelFormat(object):
    Unknown = 0
    B8G8R8A8_UNORM = 1
    R8G8B8A8_UNORM = 2
    R16G16B16A16_FLOAT = 3
    NV12 = 4
