from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.FramePixelFormat import FramePixelFormat

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FrameDescriptor:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FrameDescriptor: ...
  @classmethod
  def GetRootAsFrameDescriptor(cls, buf: bytes, offset: int) -> FrameDescriptor: ...
  @classmethod
  def FrameDescriptorBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaMajor(self) -> int: ...
  def SchemaMinor(self) -> int: ...
  def Header(self) -> CorrelationHeader | None: ...
  def FrameId(self) -> int: ...
  def CapturedAtNs(self) -> int: ...
  def Width(self) -> int: ...
  def Height(self) -> int: ...
  def Format(self) -> typing.Literal[FramePixelFormat.Unknown, FramePixelFormat.B8G8R8A8_UNORM, FramePixelFormat.R8G8B8A8_UNORM, FramePixelFormat.R16G16B16A16_FLOAT, FramePixelFormat.NV12]: ...
  def PoolSlotIndex(self) -> int: ...
  def SharedNtHandle(self) -> int: ...
  def AdapterLuid(self) -> int: ...
  def IsKeyframe(self) -> bool: ...
def FrameDescriptorStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FrameDescriptorAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int) -> None: ...
def FrameDescriptorAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int) -> None: ...
def FrameDescriptorAddHeader(builder: flatbuffers.Builder, header: uoffset) -> None: ...
def FrameDescriptorAddFrameId(builder: flatbuffers.Builder, frameId: int) -> None: ...
def FrameDescriptorAddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int) -> None: ...
def FrameDescriptorAddWidth(builder: flatbuffers.Builder, width: int) -> None: ...
def FrameDescriptorAddHeight(builder: flatbuffers.Builder, height: int) -> None: ...
def FrameDescriptorAddFormat(builder: flatbuffers.Builder, format: typing.Literal[FramePixelFormat.Unknown, FramePixelFormat.B8G8R8A8_UNORM, FramePixelFormat.R8G8B8A8_UNORM, FramePixelFormat.R16G16B16A16_FLOAT, FramePixelFormat.NV12]) -> None: ...
def FrameDescriptorAddPoolSlotIndex(builder: flatbuffers.Builder, poolSlotIndex: int) -> None: ...
def FrameDescriptorAddSharedNtHandle(builder: flatbuffers.Builder, sharedNtHandle: int) -> None: ...
def FrameDescriptorAddAdapterLuid(builder: flatbuffers.Builder, adapterLuid: int) -> None: ...
def FrameDescriptorAddIsKeyframe(builder: flatbuffers.Builder, isKeyframe: bool) -> None: ...
def FrameDescriptorEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
