from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.StageTiming import StageTiming

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class HotLoopTelemetryEvent:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> HotLoopTelemetryEvent: ...
  @classmethod
  def GetRootAsHotLoopTelemetryEvent(cls, buf: bytes, offset: int) -> HotLoopTelemetryEvent: ...
  @classmethod
  def HotLoopTelemetryEventBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaMajor(self) -> int: ...
  def SchemaMinor(self) -> int: ...
  def Header(self) -> CorrelationHeader | None: ...
  def CaptureArrivalNs(self) -> int: ...
  def ActuationDispatchNs(self) -> int: ...
  def TotalLatencyNs(self) -> int: ...
  def IsStaleDropped(self) -> bool: ...
  def QueueDepth(self) -> int: ...
  def Stages(self, i: int) -> StageTiming | None: ...
  def StagesLength(self) -> int: ...
  def StagesIsNone(self) -> bool: ...
def HotLoopTelemetryEventStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def HotLoopTelemetryEventAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int) -> None: ...
def HotLoopTelemetryEventAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int) -> None: ...
def HotLoopTelemetryEventAddHeader(builder: flatbuffers.Builder, header: uoffset) -> None: ...
def HotLoopTelemetryEventAddCaptureArrivalNs(builder: flatbuffers.Builder, captureArrivalNs: int) -> None: ...
def HotLoopTelemetryEventAddActuationDispatchNs(builder: flatbuffers.Builder, actuationDispatchNs: int) -> None: ...
def HotLoopTelemetryEventAddTotalLatencyNs(builder: flatbuffers.Builder, totalLatencyNs: int) -> None: ...
def HotLoopTelemetryEventAddIsStaleDropped(builder: flatbuffers.Builder, isStaleDropped: bool) -> None: ...
def HotLoopTelemetryEventAddQueueDepth(builder: flatbuffers.Builder, queueDepth: int) -> None: ...
def HotLoopTelemetryEventAddStages(builder: flatbuffers.Builder, stages: uoffset) -> None: ...
def HotLoopTelemetryEventStartStagesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartStagesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def HotLoopTelemetryEventEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
