# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.StageTiming import StageTiming
from typing import Optional
np = import_numpy()

# @brief End-to-end hot loop execution telemetry event
class HotLoopTelemetryEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HotLoopTelemetryEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHotLoopTelemetryEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HotLoopTelemetryEventBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x45\x31", size_prefixed=size_prefixed)

    # HotLoopTelemetryEvent
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HotLoopTelemetryEvent
    def SchemaMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # HotLoopTelemetryEvent
    def SchemaMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # HotLoopTelemetryEvent
    def Header(self) -> Optional[CorrelationHeader]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = CorrelationHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HotLoopTelemetryEvent
    def CaptureArrivalNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # HotLoopTelemetryEvent
    def ActuationDispatchNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # HotLoopTelemetryEvent
    def TotalLatencyNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # HotLoopTelemetryEvent
    def IsStaleDropped(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # HotLoopTelemetryEvent
    def QueueDepth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # HotLoopTelemetryEvent
    def Stages(self, j: int) -> Optional[StageTiming]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = StageTiming()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HotLoopTelemetryEvent
    def StagesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HotLoopTelemetryEvent
    def StagesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def HotLoopTelemetryEventStart(builder: flatbuffers.Builder):
    builder.StartObject(9)

def Start(builder: flatbuffers.Builder):
    HotLoopTelemetryEventStart(builder)

def HotLoopTelemetryEventAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    builder.PrependUint16Slot(0, schemaMajor, 1)

def AddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    HotLoopTelemetryEventAddSchemaMajor(builder, schemaMajor)

def HotLoopTelemetryEventAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    builder.PrependUint16Slot(1, schemaMinor, 0)

def AddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    HotLoopTelemetryEventAddSchemaMinor(builder, schemaMinor)

def HotLoopTelemetryEventAddHeader(builder: flatbuffers.Builder, header: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)

def AddHeader(builder: flatbuffers.Builder, header: int):
    HotLoopTelemetryEventAddHeader(builder, header)

def HotLoopTelemetryEventAddCaptureArrivalNs(builder: flatbuffers.Builder, captureArrivalNs: int):
    builder.PrependInt64Slot(3, captureArrivalNs, 0)

def AddCaptureArrivalNs(builder: flatbuffers.Builder, captureArrivalNs: int):
    HotLoopTelemetryEventAddCaptureArrivalNs(builder, captureArrivalNs)

def HotLoopTelemetryEventAddActuationDispatchNs(builder: flatbuffers.Builder, actuationDispatchNs: int):
    builder.PrependInt64Slot(4, actuationDispatchNs, 0)

def AddActuationDispatchNs(builder: flatbuffers.Builder, actuationDispatchNs: int):
    HotLoopTelemetryEventAddActuationDispatchNs(builder, actuationDispatchNs)

def HotLoopTelemetryEventAddTotalLatencyNs(builder: flatbuffers.Builder, totalLatencyNs: int):
    builder.PrependInt64Slot(5, totalLatencyNs, 0)

def AddTotalLatencyNs(builder: flatbuffers.Builder, totalLatencyNs: int):
    HotLoopTelemetryEventAddTotalLatencyNs(builder, totalLatencyNs)

def HotLoopTelemetryEventAddIsStaleDropped(builder: flatbuffers.Builder, isStaleDropped: bool):
    builder.PrependBoolSlot(6, isStaleDropped, 0)

def AddIsStaleDropped(builder: flatbuffers.Builder, isStaleDropped: bool):
    HotLoopTelemetryEventAddIsStaleDropped(builder, isStaleDropped)

def HotLoopTelemetryEventAddQueueDepth(builder: flatbuffers.Builder, queueDepth: int):
    builder.PrependUint32Slot(7, queueDepth, 0)

def AddQueueDepth(builder: flatbuffers.Builder, queueDepth: int):
    HotLoopTelemetryEventAddQueueDepth(builder, queueDepth)

def HotLoopTelemetryEventAddStages(builder: flatbuffers.Builder, stages: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(stages), 0)

def AddStages(builder: flatbuffers.Builder, stages: int):
    HotLoopTelemetryEventAddStages(builder, stages)

def HotLoopTelemetryEventStartStagesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartStagesVector(builder, numElems: int) -> int:
    return HotLoopTelemetryEventStartStagesVector(builder, numElems)

def HotLoopTelemetryEventEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return HotLoopTelemetryEventEnd(builder)
