# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Mouse button identifier
class MouseButton(object):
    None_ = 0
    Left = 1
    Right = 2
    Middle = 3
    X1 = 4
    X2 = 5
