# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Pipeline stage enumeration for telemetry
class PipelineStageCode(object):
    CaptureArrival = 0
    Preprocess = 1
    PerceptionInfer = 2
    TrackingKalman = 3
    AimPolicyPredict = 4
    TrajectoryPlan = 5
    ActuationDispatch = 6
