from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.PipelineStageCode import PipelineStageCode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class StageTiming:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> StageTiming: ...
  @classmethod
  def GetRootAsStageTiming(cls, buf: bytes, offset: int) -> StageTiming: ...
  @classmethod
  def StageTimingBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Stage(self) -> typing.Literal[PipelineStageCode.CaptureArrival, PipelineStageCode.Preprocess, PipelineStageCode.PerceptionInfer, PipelineStageCode.TrackingKalman, PipelineStageCode.AimPolicyPredict, PipelineStageCode.TrajectoryPlan, PipelineStageCode.ActuationDispatch]: ...
  def StartNs(self) -> int: ...
  def EndNs(self) -> int: ...
  def DurationNs(self) -> int: ...
def StageTimingStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def StageTimingAddStage(builder: flatbuffers.Builder, stage: typing.Literal[PipelineStageCode.CaptureArrival, PipelineStageCode.Preprocess, PipelineStageCode.PerceptionInfer, PipelineStageCode.TrackingKalman, PipelineStageCode.AimPolicyPredict, PipelineStageCode.TrajectoryPlan, PipelineStageCode.ActuationDispatch]) -> None: ...
def StageTimingAddStartNs(builder: flatbuffers.Builder, startNs: int) -> None: ...
def StageTimingAddEndNs(builder: flatbuffers.Builder, endNs: int) -> None: ...
def StageTimingAddDurationNs(builder: flatbuffers.Builder, durationNs: int) -> None: ...
def StageTimingEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
