# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# @brief Stage timing event
class StageTiming(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StageTiming()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStageTiming(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StageTimingBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x45\x31", size_prefixed=size_prefixed)

    # StageTiming
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StageTiming
    def Stage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # StageTiming
    def StartNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # StageTiming
    def EndNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # StageTiming
    def DurationNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def StageTimingStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    StageTimingStart(builder)

def StageTimingAddStage(builder: flatbuffers.Builder, stage: int):
    builder.PrependUint8Slot(0, stage, 0)

def AddStage(builder: flatbuffers.Builder, stage: int):
    StageTimingAddStage(builder, stage)

def StageTimingAddStartNs(builder: flatbuffers.Builder, startNs: int):
    builder.PrependInt64Slot(1, startNs, 0)

def AddStartNs(builder: flatbuffers.Builder, startNs: int):
    StageTimingAddStartNs(builder, startNs)

def StageTimingAddEndNs(builder: flatbuffers.Builder, endNs: int):
    builder.PrependInt64Slot(2, endNs, 0)

def AddEndNs(builder: flatbuffers.Builder, endNs: int):
    StageTimingAddEndNs(builder, endNs)

def StageTimingAddDurationNs(builder: flatbuffers.Builder, durationNs: int):
    builder.PrependInt64Slot(3, durationNs, 0)

def AddDurationNs(builder: flatbuffers.Builder, durationNs: int):
    StageTimingAddDurationNs(builder, durationNs)

def StageTimingEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return StageTimingEnd(builder)
