from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.TargetObservation import TargetObservation

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TargetObservationBatch:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TargetObservationBatch: ...
  @classmethod
  def GetRootAsTargetObservationBatch(cls, buf: bytes, offset: int) -> TargetObservationBatch: ...
  @classmethod
  def TargetObservationBatchBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaMajor(self) -> int: ...
  def SchemaMinor(self) -> int: ...
  def Header(self) -> CorrelationHeader | None: ...
  def SourceId(self) -> int: ...
  def FrameId(self) -> int: ...
  def CapturedAtNs(self) -> int: ...
  def PublishedAtNs(self) -> int: ...
  def SourceWidth(self) -> int: ...
  def SourceHeight(self) -> int: ...
  def Targets(self, i: int) -> TargetObservation | None: ...
  def TargetsLength(self) -> int: ...
  def TargetsIsNone(self) -> bool: ...
def TargetObservationBatchStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TargetObservationBatchAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int) -> None: ...
def TargetObservationBatchAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int) -> None: ...
def TargetObservationBatchAddHeader(builder: flatbuffers.Builder, header: uoffset) -> None: ...
def TargetObservationBatchAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def TargetObservationBatchAddFrameId(builder: flatbuffers.Builder, frameId: int) -> None: ...
def TargetObservationBatchAddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int) -> None: ...
def TargetObservationBatchAddPublishedAtNs(builder: flatbuffers.Builder, publishedAtNs: int) -> None: ...
def TargetObservationBatchAddSourceWidth(builder: flatbuffers.Builder, sourceWidth: int) -> None: ...
def TargetObservationBatchAddSourceHeight(builder: flatbuffers.Builder, sourceHeight: int) -> None: ...
def TargetObservationBatchAddTargets(builder: flatbuffers.Builder, targets: uoffset) -> None: ...
def TargetObservationBatchStartTargetsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTargetsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TargetObservationBatchEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
