from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.BBoxf import BBoxf
from aim.bus.v1.Covariance2f import Covariance2f
from aim.bus.v1.Vec2f import Vec2f
from aim.bus.v1.VelocityHint import VelocityHint
from aim.bus.v1.Visibility import Visibility

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TargetObservation:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TargetObservation: ...
  @classmethod
  def GetRootAsTargetObservation(cls, buf: bytes, offset: int) -> TargetObservation: ...
  @classmethod
  def TargetObservationBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SourceId(self) -> int: ...
  def FrameId(self) -> int: ...
  def CapturedAtNs(self) -> int: ...
  def CenterPx(self) -> Vec2f | None: ...
  def CenterNorm(self) -> Vec2f | None: ...
  def BboxPx(self) -> BBoxf | None: ...
  def EffectiveRadiusPx(self) -> float: ...
  def Confidence(self) -> float: ...
  def CovariancePx2(self) -> Covariance2f | None: ...
  def Velocity(self) -> VelocityHint | None: ...
  def Visibility(self) -> typing.Literal[Visibility.Visible, Visibility.Partial, Visibility.Predicted]: ...
  def TargetValue(self) -> float: ...
  def SemanticId(self) -> int: ...
def TargetObservationStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TargetObservationAddSourceId(builder: flatbuffers.Builder, sourceId: int) -> None: ...
def TargetObservationAddFrameId(builder: flatbuffers.Builder, frameId: int) -> None: ...
def TargetObservationAddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int) -> None: ...
def TargetObservationAddCenterPx(builder: flatbuffers.Builder, centerPx: uoffset) -> None: ...
def TargetObservationAddCenterNorm(builder: flatbuffers.Builder, centerNorm: uoffset) -> None: ...
def TargetObservationAddBboxPx(builder: flatbuffers.Builder, bboxPx: uoffset) -> None: ...
def TargetObservationAddEffectiveRadiusPx(builder: flatbuffers.Builder, effectiveRadiusPx: float) -> None: ...
def TargetObservationAddConfidence(builder: flatbuffers.Builder, confidence: float) -> None: ...
def TargetObservationAddCovariancePx2(builder: flatbuffers.Builder, covariancePx2: uoffset) -> None: ...
def TargetObservationAddVelocity(builder: flatbuffers.Builder, velocity: uoffset) -> None: ...
def TargetObservationAddVisibility(builder: flatbuffers.Builder, visibility: typing.Literal[Visibility.Visible, Visibility.Partial, Visibility.Predicted]) -> None: ...
def TargetObservationAddTargetValue(builder: flatbuffers.Builder, targetValue: float) -> None: ...
def TargetObservationAddSemanticId(builder: flatbuffers.Builder, semanticId: int) -> None: ...
def TargetObservationEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
