# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.TargetObservation import TargetObservation
from typing import Optional
np = import_numpy()

# @brief Batch of canonical target observations for a single frame
class TargetObservationBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TargetObservationBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTargetObservationBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TargetObservationBatchBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x4F\x42\x31", size_prefixed=size_prefixed)

    # TargetObservationBatch
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TargetObservationBatch
    def SchemaMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # TargetObservationBatch
    def SchemaMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TargetObservationBatch
    def Header(self) -> Optional[CorrelationHeader]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = CorrelationHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TargetObservationBatch
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TargetObservationBatch
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TargetObservationBatch
    def CapturedAtNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TargetObservationBatch
    def PublishedAtNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TargetObservationBatch
    def SourceWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1920

    # TargetObservationBatch
    def SourceHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1080

    # TargetObservationBatch
    def Targets(self, j: int) -> Optional[TargetObservation]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TargetObservation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TargetObservationBatch
    def TargetsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TargetObservationBatch
    def TargetsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def TargetObservationBatchStart(builder: flatbuffers.Builder):
    builder.StartObject(10)

def Start(builder: flatbuffers.Builder):
    TargetObservationBatchStart(builder)

def TargetObservationBatchAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    builder.PrependUint16Slot(0, schemaMajor, 1)

def AddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    TargetObservationBatchAddSchemaMajor(builder, schemaMajor)

def TargetObservationBatchAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    builder.PrependUint16Slot(1, schemaMinor, 0)

def AddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    TargetObservationBatchAddSchemaMinor(builder, schemaMinor)

def TargetObservationBatchAddHeader(builder: flatbuffers.Builder, header: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)

def AddHeader(builder: flatbuffers.Builder, header: int):
    TargetObservationBatchAddHeader(builder, header)

def TargetObservationBatchAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint64Slot(3, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    TargetObservationBatchAddSourceId(builder, sourceId)

def TargetObservationBatchAddFrameId(builder: flatbuffers.Builder, frameId: int):
    builder.PrependUint64Slot(4, frameId, 0)

def AddFrameId(builder: flatbuffers.Builder, frameId: int):
    TargetObservationBatchAddFrameId(builder, frameId)

def TargetObservationBatchAddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int):
    builder.PrependInt64Slot(5, capturedAtNs, 0)

def AddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int):
    TargetObservationBatchAddCapturedAtNs(builder, capturedAtNs)

def TargetObservationBatchAddPublishedAtNs(builder: flatbuffers.Builder, publishedAtNs: int):
    builder.PrependInt64Slot(6, publishedAtNs, 0)

def AddPublishedAtNs(builder: flatbuffers.Builder, publishedAtNs: int):
    TargetObservationBatchAddPublishedAtNs(builder, publishedAtNs)

def TargetObservationBatchAddSourceWidth(builder: flatbuffers.Builder, sourceWidth: int):
    builder.PrependUint32Slot(7, sourceWidth, 1920)

def AddSourceWidth(builder: flatbuffers.Builder, sourceWidth: int):
    TargetObservationBatchAddSourceWidth(builder, sourceWidth)

def TargetObservationBatchAddSourceHeight(builder: flatbuffers.Builder, sourceHeight: int):
    builder.PrependUint32Slot(8, sourceHeight, 1080)

def AddSourceHeight(builder: flatbuffers.Builder, sourceHeight: int):
    TargetObservationBatchAddSourceHeight(builder, sourceHeight)

def TargetObservationBatchAddTargets(builder: flatbuffers.Builder, targets: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(targets), 0)

def AddTargets(builder: flatbuffers.Builder, targets: int):
    TargetObservationBatchAddTargets(builder, targets)

def TargetObservationBatchStartTargetsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTargetsVector(builder, numElems: int) -> int:
    return TargetObservationBatchStartTargetsVector(builder, numElems)

def TargetObservationBatchEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TargetObservationBatchEnd(builder)
