# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.BBoxf import BBoxf
from aim.bus.v1.Covariance2f import Covariance2f
from aim.bus.v1.Vec2f import Vec2f
from aim.bus.v1.VelocityHint import VelocityHint
from typing import Optional
np = import_numpy()

# @brief Canonical visual target observation from perception
class TargetObservation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TargetObservation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTargetObservation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TargetObservationBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x4F\x42\x31", size_prefixed=size_prefixed)

    # TargetObservation
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TargetObservation
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TargetObservation
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TargetObservation
    def CapturedAtNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TargetObservation
    def CenterPx(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TargetObservation
    def CenterNorm(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TargetObservation
    def BboxPx(self) -> Optional[BBoxf]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = BBoxf()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TargetObservation
    def EffectiveRadiusPx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TargetObservation
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TargetObservation
    def CovariancePx2(self) -> Optional[Covariance2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = Covariance2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TargetObservation
    def Velocity(self) -> Optional[VelocityHint]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VelocityHint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TargetObservation
    def Visibility(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TargetObservation
    def TargetValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # TargetObservation
    def SemanticId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def TargetObservationStart(builder: flatbuffers.Builder):
    builder.StartObject(13)

def Start(builder: flatbuffers.Builder):
    TargetObservationStart(builder)

def TargetObservationAddSourceId(builder: flatbuffers.Builder, sourceId: int):
    builder.PrependUint64Slot(0, sourceId, 0)

def AddSourceId(builder: flatbuffers.Builder, sourceId: int):
    TargetObservationAddSourceId(builder, sourceId)

def TargetObservationAddFrameId(builder: flatbuffers.Builder, frameId: int):
    builder.PrependUint64Slot(1, frameId, 0)

def AddFrameId(builder: flatbuffers.Builder, frameId: int):
    TargetObservationAddFrameId(builder, frameId)

def TargetObservationAddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int):
    builder.PrependInt64Slot(2, capturedAtNs, 0)

def AddCapturedAtNs(builder: flatbuffers.Builder, capturedAtNs: int):
    TargetObservationAddCapturedAtNs(builder, capturedAtNs)

def TargetObservationAddCenterPx(builder: flatbuffers.Builder, centerPx: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(centerPx), 0)

def AddCenterPx(builder: flatbuffers.Builder, centerPx: Any):
    TargetObservationAddCenterPx(builder, centerPx)

def TargetObservationAddCenterNorm(builder: flatbuffers.Builder, centerNorm: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(centerNorm), 0)

def AddCenterNorm(builder: flatbuffers.Builder, centerNorm: Any):
    TargetObservationAddCenterNorm(builder, centerNorm)

def TargetObservationAddBboxPx(builder: flatbuffers.Builder, bboxPx: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(bboxPx), 0)

def AddBboxPx(builder: flatbuffers.Builder, bboxPx: Any):
    TargetObservationAddBboxPx(builder, bboxPx)

def TargetObservationAddEffectiveRadiusPx(builder: flatbuffers.Builder, effectiveRadiusPx: float):
    builder.PrependFloat32Slot(6, effectiveRadiusPx, 0.0)

def AddEffectiveRadiusPx(builder: flatbuffers.Builder, effectiveRadiusPx: float):
    TargetObservationAddEffectiveRadiusPx(builder, effectiveRadiusPx)

def TargetObservationAddConfidence(builder: flatbuffers.Builder, confidence: float):
    builder.PrependFloat32Slot(7, confidence, 0.0)

def AddConfidence(builder: flatbuffers.Builder, confidence: float):
    TargetObservationAddConfidence(builder, confidence)

def TargetObservationAddCovariancePx2(builder: flatbuffers.Builder, covariancePx2: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(covariancePx2), 0)

def AddCovariancePx2(builder: flatbuffers.Builder, covariancePx2: Any):
    TargetObservationAddCovariancePx2(builder, covariancePx2)

def TargetObservationAddVelocity(builder: flatbuffers.Builder, velocity: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(velocity), 0)

def AddVelocity(builder: flatbuffers.Builder, velocity: int):
    TargetObservationAddVelocity(builder, velocity)

def TargetObservationAddVisibility(builder: flatbuffers.Builder, visibility: int):
    builder.PrependUint8Slot(10, visibility, 0)

def AddVisibility(builder: flatbuffers.Builder, visibility: int):
    TargetObservationAddVisibility(builder, visibility)

def TargetObservationAddTargetValue(builder: flatbuffers.Builder, targetValue: float):
    builder.PrependFloat32Slot(11, targetValue, 1.0)

def AddTargetValue(builder: flatbuffers.Builder, targetValue: float):
    TargetObservationAddTargetValue(builder, targetValue)

def TargetObservationAddSemanticId(builder: flatbuffers.Builder, semanticId: int):
    builder.PrependUint32Slot(12, semanticId, 0)

def AddSemanticId(builder: flatbuffers.Builder, semanticId: int):
    TargetObservationAddSemanticId(builder, semanticId)

def TargetObservationEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TargetObservationEnd(builder)
