from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.TrackedTarget import TrackedTarget

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TrackedTargetBatch:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TrackedTargetBatch: ...
  @classmethod
  def GetRootAsTrackedTargetBatch(cls, buf: bytes, offset: int) -> TrackedTargetBatch: ...
  @classmethod
  def TrackedTargetBatchBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SchemaMajor(self) -> int: ...
  def SchemaMinor(self) -> int: ...
  def Header(self) -> CorrelationHeader | None: ...
  def FrameId(self) -> int: ...
  def TimestampNs(self) -> int: ...
  def Tracks(self, i: int) -> TrackedTarget | None: ...
  def TracksLength(self) -> int: ...
  def TracksIsNone(self) -> bool: ...
def TrackedTargetBatchStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TrackedTargetBatchAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int) -> None: ...
def TrackedTargetBatchAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int) -> None: ...
def TrackedTargetBatchAddHeader(builder: flatbuffers.Builder, header: uoffset) -> None: ...
def TrackedTargetBatchAddFrameId(builder: flatbuffers.Builder, frameId: int) -> None: ...
def TrackedTargetBatchAddTimestampNs(builder: flatbuffers.Builder, timestampNs: int) -> None: ...
def TrackedTargetBatchAddTracks(builder: flatbuffers.Builder, tracks: uoffset) -> None: ...
def TrackedTargetBatchStartTracksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTracksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TrackedTargetBatchEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
