from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.Covariance2f import Covariance2f
from aim.bus.v1.TrackState import TrackState
from aim.bus.v1.Vec2f import Vec2f

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TrackedTarget:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TrackedTarget: ...
  @classmethod
  def GetRootAsTrackedTarget(cls, buf: bytes, offset: int) -> TrackedTarget: ...
  @classmethod
  def TrackedTargetBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TrackId(self) -> int: ...
  def State(self) -> typing.Literal[TrackState.Tentative, TrackState.Confirmed, TrackState.Occluded, TrackState.Coasting, TrackState.Lost]: ...
  def TotalVisibleFrames(self) -> int: ...
  def TotalMissedFrames(self) -> int: ...
  def FilteredCenterPx(self) -> Vec2f | None: ...
  def FilteredVelocityPxPerS(self) -> Vec2f | None: ...
  def FilteredAccelerationPxPerS2(self) -> Vec2f | None: ...
  def CovariancePx2(self) -> Covariance2f | None: ...
  def PredictedCenterPx(self) -> Vec2f | None: ...
  def PredictionTimeNs(self) -> int: ...
  def EffectiveRadiusPx(self) -> float: ...
  def Confidence(self) -> float: ...
  def TargetValue(self) -> float: ...
  def SemanticId(self) -> int: ...
def TrackedTargetStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TrackedTargetAddTrackId(builder: flatbuffers.Builder, trackId: int) -> None: ...
def TrackedTargetAddState(builder: flatbuffers.Builder, state: typing.Literal[TrackState.Tentative, TrackState.Confirmed, TrackState.Occluded, TrackState.Coasting, TrackState.Lost]) -> None: ...
def TrackedTargetAddTotalVisibleFrames(builder: flatbuffers.Builder, totalVisibleFrames: int) -> None: ...
def TrackedTargetAddTotalMissedFrames(builder: flatbuffers.Builder, totalMissedFrames: int) -> None: ...
def TrackedTargetAddFilteredCenterPx(builder: flatbuffers.Builder, filteredCenterPx: uoffset) -> None: ...
def TrackedTargetAddFilteredVelocityPxPerS(builder: flatbuffers.Builder, filteredVelocityPxPerS: uoffset) -> None: ...
def TrackedTargetAddFilteredAccelerationPxPerS2(builder: flatbuffers.Builder, filteredAccelerationPxPerS2: uoffset) -> None: ...
def TrackedTargetAddCovariancePx2(builder: flatbuffers.Builder, covariancePx2: uoffset) -> None: ...
def TrackedTargetAddPredictedCenterPx(builder: flatbuffers.Builder, predictedCenterPx: uoffset) -> None: ...
def TrackedTargetAddPredictionTimeNs(builder: flatbuffers.Builder, predictionTimeNs: int) -> None: ...
def TrackedTargetAddEffectiveRadiusPx(builder: flatbuffers.Builder, effectiveRadiusPx: float) -> None: ...
def TrackedTargetAddConfidence(builder: flatbuffers.Builder, confidence: float) -> None: ...
def TrackedTargetAddTargetValue(builder: flatbuffers.Builder, targetValue: float) -> None: ...
def TrackedTargetAddSemanticId(builder: flatbuffers.Builder, semanticId: int) -> None: ...
def TrackedTargetEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
