# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.CorrelationHeader import CorrelationHeader
from aim.bus.v1.TrackedTarget import TrackedTarget
from typing import Optional
np = import_numpy()

# @brief Batch of tracked targets published by tracking stage
class TrackedTargetBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackedTargetBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackedTargetBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TrackedTargetBatchBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x54\x31", size_prefixed=size_prefixed)

    # TrackedTargetBatch
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackedTargetBatch
    def SchemaMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # TrackedTargetBatch
    def SchemaMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TrackedTargetBatch
    def Header(self) -> Optional[CorrelationHeader]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = CorrelationHeader()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackedTargetBatch
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TrackedTargetBatch
    def TimestampNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TrackedTargetBatch
    def Tracks(self, j: int) -> Optional[TrackedTarget]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TrackedTarget()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackedTargetBatch
    def TracksLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackedTargetBatch
    def TracksIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def TrackedTargetBatchStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    TrackedTargetBatchStart(builder)

def TrackedTargetBatchAddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    builder.PrependUint16Slot(0, schemaMajor, 1)

def AddSchemaMajor(builder: flatbuffers.Builder, schemaMajor: int):
    TrackedTargetBatchAddSchemaMajor(builder, schemaMajor)

def TrackedTargetBatchAddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    builder.PrependUint16Slot(1, schemaMinor, 0)

def AddSchemaMinor(builder: flatbuffers.Builder, schemaMinor: int):
    TrackedTargetBatchAddSchemaMinor(builder, schemaMinor)

def TrackedTargetBatchAddHeader(builder: flatbuffers.Builder, header: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(header), 0)

def AddHeader(builder: flatbuffers.Builder, header: int):
    TrackedTargetBatchAddHeader(builder, header)

def TrackedTargetBatchAddFrameId(builder: flatbuffers.Builder, frameId: int):
    builder.PrependUint64Slot(3, frameId, 0)

def AddFrameId(builder: flatbuffers.Builder, frameId: int):
    TrackedTargetBatchAddFrameId(builder, frameId)

def TrackedTargetBatchAddTimestampNs(builder: flatbuffers.Builder, timestampNs: int):
    builder.PrependInt64Slot(4, timestampNs, 0)

def AddTimestampNs(builder: flatbuffers.Builder, timestampNs: int):
    TrackedTargetBatchAddTimestampNs(builder, timestampNs)

def TrackedTargetBatchAddTracks(builder: flatbuffers.Builder, tracks: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(tracks), 0)

def AddTracks(builder: flatbuffers.Builder, tracks: int):
    TrackedTargetBatchAddTracks(builder, tracks)

def TrackedTargetBatchStartTracksVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartTracksVector(builder, numElems: int) -> int:
    return TrackedTargetBatchStartTracksVector(builder, numElems)

def TrackedTargetBatchEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TrackedTargetBatchEnd(builder)
