# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.Covariance2f import Covariance2f
from aim.bus.v1.Vec2f import Vec2f
from typing import Optional
np = import_numpy()

# @brief Single tracked target state estimated by Kalman/lifecycle tracker
class TrackedTarget(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackedTarget()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackedTarget(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TrackedTargetBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x54\x54\x31", size_prefixed=size_prefixed)

    # TrackedTarget
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackedTarget
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TrackedTarget
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # TrackedTarget
    def TotalVisibleFrames(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1

    # TrackedTarget
    def TotalMissedFrames(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TrackedTarget
    def FilteredCenterPx(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackedTarget
    def FilteredVelocityPxPerS(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackedTarget
    def FilteredAccelerationPxPerS2(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackedTarget
    def CovariancePx2(self) -> Optional[Covariance2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = Covariance2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackedTarget
    def PredictedCenterPx(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackedTarget
    def PredictionTimeNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TrackedTarget
    def EffectiveRadiusPx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TrackedTarget
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TrackedTarget
    def TargetValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # TrackedTarget
    def SemanticId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def TrackedTargetStart(builder: flatbuffers.Builder):
    builder.StartObject(14)

def Start(builder: flatbuffers.Builder):
    TrackedTargetStart(builder)

def TrackedTargetAddTrackId(builder: flatbuffers.Builder, trackId: int):
    builder.PrependUint64Slot(0, trackId, 0)

def AddTrackId(builder: flatbuffers.Builder, trackId: int):
    TrackedTargetAddTrackId(builder, trackId)

def TrackedTargetAddState(builder: flatbuffers.Builder, state: int):
    builder.PrependUint8Slot(1, state, 1)

def AddState(builder: flatbuffers.Builder, state: int):
    TrackedTargetAddState(builder, state)

def TrackedTargetAddTotalVisibleFrames(builder: flatbuffers.Builder, totalVisibleFrames: int):
    builder.PrependUint32Slot(2, totalVisibleFrames, 1)

def AddTotalVisibleFrames(builder: flatbuffers.Builder, totalVisibleFrames: int):
    TrackedTargetAddTotalVisibleFrames(builder, totalVisibleFrames)

def TrackedTargetAddTotalMissedFrames(builder: flatbuffers.Builder, totalMissedFrames: int):
    builder.PrependUint32Slot(3, totalMissedFrames, 0)

def AddTotalMissedFrames(builder: flatbuffers.Builder, totalMissedFrames: int):
    TrackedTargetAddTotalMissedFrames(builder, totalMissedFrames)

def TrackedTargetAddFilteredCenterPx(builder: flatbuffers.Builder, filteredCenterPx: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(filteredCenterPx), 0)

def AddFilteredCenterPx(builder: flatbuffers.Builder, filteredCenterPx: Any):
    TrackedTargetAddFilteredCenterPx(builder, filteredCenterPx)

def TrackedTargetAddFilteredVelocityPxPerS(builder: flatbuffers.Builder, filteredVelocityPxPerS: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(filteredVelocityPxPerS), 0)

def AddFilteredVelocityPxPerS(builder: flatbuffers.Builder, filteredVelocityPxPerS: Any):
    TrackedTargetAddFilteredVelocityPxPerS(builder, filteredVelocityPxPerS)

def TrackedTargetAddFilteredAccelerationPxPerS2(builder: flatbuffers.Builder, filteredAccelerationPxPerS2: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(filteredAccelerationPxPerS2), 0)

def AddFilteredAccelerationPxPerS2(builder: flatbuffers.Builder, filteredAccelerationPxPerS2: Any):
    TrackedTargetAddFilteredAccelerationPxPerS2(builder, filteredAccelerationPxPerS2)

def TrackedTargetAddCovariancePx2(builder: flatbuffers.Builder, covariancePx2: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(covariancePx2), 0)

def AddCovariancePx2(builder: flatbuffers.Builder, covariancePx2: Any):
    TrackedTargetAddCovariancePx2(builder, covariancePx2)

def TrackedTargetAddPredictedCenterPx(builder: flatbuffers.Builder, predictedCenterPx: Any):
    builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(predictedCenterPx), 0)

def AddPredictedCenterPx(builder: flatbuffers.Builder, predictedCenterPx: Any):
    TrackedTargetAddPredictedCenterPx(builder, predictedCenterPx)

def TrackedTargetAddPredictionTimeNs(builder: flatbuffers.Builder, predictionTimeNs: int):
    builder.PrependInt64Slot(9, predictionTimeNs, 0)

def AddPredictionTimeNs(builder: flatbuffers.Builder, predictionTimeNs: int):
    TrackedTargetAddPredictionTimeNs(builder, predictionTimeNs)

def TrackedTargetAddEffectiveRadiusPx(builder: flatbuffers.Builder, effectiveRadiusPx: float):
    builder.PrependFloat32Slot(10, effectiveRadiusPx, 0.0)

def AddEffectiveRadiusPx(builder: flatbuffers.Builder, effectiveRadiusPx: float):
    TrackedTargetAddEffectiveRadiusPx(builder, effectiveRadiusPx)

def TrackedTargetAddConfidence(builder: flatbuffers.Builder, confidence: float):
    builder.PrependFloat32Slot(11, confidence, 0.0)

def AddConfidence(builder: flatbuffers.Builder, confidence: float):
    TrackedTargetAddConfidence(builder, confidence)

def TrackedTargetAddTargetValue(builder: flatbuffers.Builder, targetValue: float):
    builder.PrependFloat32Slot(12, targetValue, 1.0)

def AddTargetValue(builder: flatbuffers.Builder, targetValue: float):
    TrackedTargetAddTargetValue(builder, targetValue)

def TrackedTargetAddSemanticId(builder: flatbuffers.Builder, semanticId: int):
    builder.PrependUint32Slot(13, semanticId, 0)

def AddSemanticId(builder: flatbuffers.Builder, semanticId: int):
    TrackedTargetAddSemanticId(builder, semanticId)

def TrackedTargetEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TrackedTargetEnd(builder)
