# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Tracking filter lifecycle state
class TrackState(object):
    Tentative = 0
    Confirmed = 1
    Occluded = 2
    Coasting = 3
    Lost = 4
