from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from aim.bus.v1.Vec2f import Vec2f

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class VelocityHint:
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> VelocityHint: ...
  @classmethod
  def GetRootAsVelocityHint(cls, buf: bytes, offset: int) -> VelocityHint: ...
  @classmethod
  def VelocityHintBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PixelsPerSecond(self) -> Vec2f | None: ...
  def Confidence(self) -> float: ...
def VelocityHintStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def VelocityHintAddPixelsPerSecond(builder: flatbuffers.Builder, pixelsPerSecond: uoffset) -> None: ...
def VelocityHintAddConfidence(builder: flatbuffers.Builder, confidence: float) -> None: ...
def VelocityHintEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...
