# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from aim.bus.v1.Vec2f import Vec2f
from typing import Optional
np = import_numpy()

# @brief Optical flow / model velocity hint
class VelocityHint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VelocityHint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVelocityHint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def VelocityHintBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x41\x4F\x42\x31", size_prefixed=size_prefixed)

    # VelocityHint
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VelocityHint
    def PixelsPerSecond(self) -> Optional[Vec2f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec2f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VelocityHint
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def VelocityHintStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    VelocityHintStart(builder)

def VelocityHintAddPixelsPerSecond(builder: flatbuffers.Builder, pixelsPerSecond: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pixelsPerSecond), 0)

def AddPixelsPerSecond(builder: flatbuffers.Builder, pixelsPerSecond: Any):
    VelocityHintAddPixelsPerSecond(builder, pixelsPerSecond)

def VelocityHintAddConfidence(builder: flatbuffers.Builder, confidence: float):
    builder.PrependFloat32Slot(1, confidence, 0.0)

def AddConfidence(builder: flatbuffers.Builder, confidence: float):
    VelocityHintAddConfidence(builder, confidence)

def VelocityHintEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return VelocityHintEnd(builder)
