# automatically generated by the FlatBuffers compiler, do not modify

# namespace: v1

# @brief Target visibility classification
class Visibility(object):
    Visible = 0
    Partial = 1
    Predicted = 2
